# backend/base_agent.py

from abc import ABC, abstractmethod
from typing import Generator, List, Dict
from google.genai import types


class BaseAgent(ABC):
    """
    An abstract base class for all specialized agent plugins.
    Each agent is a self-contained unit responsible for handling a specific type of task.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """
        Returns the unique, machine-readable name of the agent.
        e.g., "research_agent"
        """
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """
        Returns a detailed, natural language description of what the agent does.
        This is used by the router to decide when to deploy this agent.
        """
        pass

    @property
    @abstractmethod
    def ui_component(self) -> str:
        """
        Returns the name of the frontend React component to render for this agent's output.
        This allows for dynamic UI based on the agent being used.
        e.g., "AgentProcess", "ResearchTimeline"
        """
        pass

    @abstractmethod
    def execute(
        self,
        query: str,
        chat_history: List[Dict],
        user_id: int,
        model_name: str,
        system_prompt: str,
        tool_declarations: List[types.FunctionDeclaration],
        personalization_prompt: str = "",
        router_response: str = "",
        original_user_query: str = "",
    ) -> Generator[str, None, None]:
        """
        Executes the agent's logic. This method MUST be a generator that yields
        Server-Sent Events (SSE) formatted strings for the frontend.

        Args:
            query (str): The specific, rewritten query from the router for the agent.
            chat_history (List[Dict]): The history of the conversation, including the latest user message.
            user_id (int): The ID of the current user.
            model_name (str): The conversational model to use.
            system_prompt (str): The fully-formed system prompt, including persona and capabilities.
            tool_declarations (List[types.FunctionDeclaration]): The list of Gemini-formatted tools the agent can use.
            personalization_prompt (str, optional): Persona instructions. Defaults to "".
            router_response (str, optional): The text generated by the router before calling the agent. Defaults to "".
            original_user_query (str, optional): The original, unmodified query from the user. Defaults to "".
        """
        pass
