export function usage(): string {
  return [
    "Usage: skyth [OPTIONS] COMMAND [ARGS]...",
    "",
    "skyth - Personal AI Assistant",
    "",
    "Options:",
    "  --version, -v",
    "  --install-completion",
    "  --show-completion",
    "  --help",
    "",
    "Commands:",
    "  init       Alias for `skyth run onboarding`.",
    "  onboard    Interactive onboarding wizard.",
    "  gateway    Start the skyth gateway.",
    "  agent      Interact with the agent directly.",
    "  status     Show skyth status.",
    "  run        Run workflows",
    "  channels   Manage channels",
    "  pairing    Pair channel users",
    "  cron       Manage scheduled tasks",
    "  configure  Configure one setting",
    "  migrate    Migrate workspace/config state",
    "  provider   Manage providers",
    "  auth       Manage authentication (API keys)",
    "",
    "Run onboarding:",
    "  skyth run onboarding [options]",
    "  skyth init [options]",
    "  skyth onboard [--install-daemon|--no-install-daemon]",
    "",
    "Gateway:",
    "  skyth gateway --port 18797 --verbose --print-logs",
    "    --print-logs       show channel/runtime component logs",
    "    --verbose          include high-frequency trace logs and timestamps",
    "    --gateway-token T  token for WS client auth (or SKYTH_GATEWAY_TOKEN env)",
    "    --no-ws            disable WebSocket gateway server",
    "    --no-discovery     disable mDNS/Bonjour advertisement",
    "",
    "Gateway discover:",
    "  skyth gateway discover [--timeout-ms 5000]",
    "",
    "Cron add:",
    "  skyth cron add --name NAME --message MSG --cron EXPR [--tz ZONE]",
    "",
    "Pairing:",
    "  skyth pairing telegram [--token TOKEN] [--code ABC-123] [--timeout-ms 120000]",
    "  skyth pairing telegram --reauth",
    "",
    "Configure:",
    "  skyth configure username tammy",
    "  skyth configure password --value secret",
    "  skyth configure provider openai --api-key sk-...",
    "  skyth configure model openai/gpt-4.1",
    "  skyth configure channels telegram",
    "  skyth configure channels telegram --json '{\"token\":\"bot123\"}' --enable",
    "",
    "Migrate:",
    "  skyth migrate from openclaw",
    "  skyth migrate to openclaw",
    "",
    "Auth:",
    "  skyth auth create-key --name 'my-script' --scopes read,write",
    "  skyth auth revoke-key key_uuid",
    "  skyth auth list-keys",
    "  skyth auth token create",
    "  skyth auth token view",
    "  skyth auth token add-node --channel telegram --code ABC-123",
  ].join("\n");
}
